version: "3.5"

services: 
  mysql: 
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_USER: wordpress
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  solr: 
    image: "solr:8"
    ports: 
      - "8983:8983"
    restart: always
    volumes: 
        - "./data/solr:/var/solr"
  stanbol: 
    environment: 
      - "JAVA_OPTS=-Xmx1g -XX:MaxPermSize=256m"
    image: mxr576/stanbol
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
        - "./data/stanbol/indexes:/stanbol/indexes"
  wordpress: 
    depends_on: 
      - mysql
      - stanbol
      - solr
    environment: 
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
    image: "wordpress:latest"
    ports: 
      - "8000:80"
    restart: always
volumes:
    db_data: {}
